feat: 修改 get command 的query 参数
edgexfoundry/edgex-ui-go pull request #612
Opened 2023-05-18 07:31 UTC by Ambition-J

Get command 里面 ds-pushevent and ds-returnevent 的query parameters，值改为true or false

2023-05-18 21:41 UTC, ajcasagrande commented on web/package-lock.json
package-lock.json has been downgraded to version 1 from version 2. Please upgrade your npm and re-generate the lock file.

2023-05-19 02:28 UTC, cloudxxx8 requested changes
there are too many unlrelated changes
please rebase the code

2023-05-23 09:24 UTC, cloudxxx8 commented
@Ambition-J are you able to rebase this PR?

2023-05-24 04:06 UTC, cloudxxx8 approved these changes
LGTM

2023-05-24 04:07 UTC, merged