fix AppService in the UI by adding a second auth field
edgexfoundry/edgex-ui-go pull request #700
Opened 2024-02-10 13:49 UTC by dovholuknf

closes #672 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)

## Testing Instructions
* check out this branch
* issue `make docker` to create a new ui image
* enable security
* update `docker-compose.yml` with the local dev UI image
* bring up the docker environment
* open the UI see the new dialog
* from `edgex-compose` issue `make get-token` use this as the "Gateway Token" and `make get-consul-acl-token` for the "ACL Token"

## New Dependency Instructions (If applicable)
none

2024-02-10 14:15 UTC, dovholuknf commented
Thanks to @rgallettonf for helping out!

2024-02-11 16:51 UTC, lenny-intel commented
@dovholuknf , please fix you commit message and PR title to add `:` after `fix`

2024-02-11 18:19 UTC, dovholuknf commented
> @dovholuknf , please fix you commit message and PR title to add `:` after `fix`

is there some kind of strange bug by having the word 'fix' twice? i commited with `fix: fix AppService`.... 
![image](https://github.com/edgexfoundry/edgex-ui-go/assets/46322585/9ebc839d-92d5-4423-96ac-ede10b789d60)

2024-02-12 16:35 UTC, lenny-intel requested changes
One minor issue. Thanks for the PR!

2024-02-12 16:35 UTC, lenny-intel commented on web/src/app/guards/auth/login/login.component.html
> +                      <small i18n>the registry token is invalid!</small>
```suggestion
                      <small i18n>the ACL token is invalid!</small>
```

2024-02-12 16:40 UTC, dovholuknf commented on web/src/app/guards/auth/login/login.component.html
> +                      <small i18n>the registry token is invalid!</small>
changed

2024-02-12 16:45 UTC, lenny-intel commented
@dovholuknf , I think we need to make the ACL token optional. Something like

`ACL Token (required for App Service)`

2024-02-12 16:47 UTC, lenny-intel commented
We also need to update the doc at [How to get access token?](https://docs.edgexfoundry.org/3.0/security/Ch-Authenticating/#how-to-make-authenticated-edgex-calls) to include how to get the ACL token.

2024-02-13 19:11 UTC, dovholuknf commented
two new commits pushed. here's a gif of it in action:

![new-edgex-ui-login](https://github.com/edgexfoundry/edgex-ui-go/assets/46322585/092f4b04-140d-42c1-ad09-655327d1a879)

2024-02-13 22:41 UTC, lenny-intel approved these changes
LGTM and works great.

2024-02-14 15:31 UTC, lenny-intel approved these changes
LGTM

2024-02-14 15:31 UTC, merged